"""Re-collect executed q_live along the 239 teacher plans with deployment MCC.

Background
----------
D1 training data already uses (q_live observation, q_live label), but the
q_live compensation distribution it records was generated by the collection-era
MCC (3.0 N desired force, per-finger (3,3,3,4) N, loss frames 6, recovery
confirm 4, max normal offset 3.0 mm, rate limit 0.18, ema 0.65), while
deployment uses the frozen §32 MCC (1.5 N, loss frames 8, sensor normal memory
20, runtime recovery limit 0.02 rad, search step 0.10 mm, recovery decay 0.98
@ force ratio 0.5).  The compensation shape the model trains on therefore
differs from the compensation shape it deploys with.

This driver replays every recorded teacher q through the same actuator/MCC
stack used at deployment (`--mode collect_executed` in deploy_dp_inverse.py):
DP inference is skipped, desired = data["q_hand"][t] for every frame, and the
closed-loop rollout records q_live + palm-frame contact + palm pose per step
with the deployment MCC settings.  The per-episode rollout H5s are then
converted to a DP training file by export_executed_q_live.py.

Each episode runs in its own subprocess (headless CPU physics) so episodes can
run in parallel and resume independently.  A rollout H5 whose size matches the
expected frames is treated as complete and skipped on resume.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import h5py

SCRIPT_DIR = Path(__file__).resolve().parent
DEPLOY = SCRIPT_DIR / "deploy_dp_inverse.py"

# Frozen §32 deployment MCC settings; explicit overrides replace them.
FROZEN_MCC_DEFAULTS = {
    "--execution-layer": "fullhand_mcc",
    "--mcc-desired-force": "1.5",
    "--mcc-runtime-loss-frames": "8",
    "--mcc-sensor-normal-memory-frames": "20",
    "--mcc-runtime-recovery-limit-rad": "0.02",
    "--mcc-contact-search-step-mm": "0.10",
    "--mcc-recovery-offset-decay": "0.98",
    "--mcc-recovery-decay-force-ratio": "0.5",
}


def _expected_frames(teacher_path: Path, episode_id: int, max_steps: int) -> int:
    with h5py.File(teacher_path, "r") as file:
        episode_ids = file["episode_id"][:, 0]
        count = int((episode_ids == episode_id).sum())
    return count if max_steps <= 0 else min(count, max_steps)


def _rollout_complete(path: Path, expected_frames: int) -> bool:
    if not path.is_file():
        return False
    try:
        with h5py.File(path, "r") as file:
            frames = int(file["episode_step"].shape[0])
    except (OSError, KeyError):
        return False
    return frames >= expected_frames


def _run_episode(
    teacher_path: Path,
    model_path: Path,
    out_dir: Path,
    episode_id: int,
    max_steps: int,
    extra_args: list[str],
    python: str,
) -> dict[str, object]:
    rollout = out_dir / f"ep{episode_id:04d}.h5"
    report = out_dir / "reports" / f"ep{episode_id:04d}.csv"
    log = out_dir / "logs" / f"ep{episode_id:04d}.log"
    command = [
        python,
        str(DEPLOY),
        "--mode",
        "collect_executed",
        "--file",
        str(teacher_path),
        "--episode-id",
        str(episode_id),
        "--model",
        str(model_path),
        "--rollout-h5",
        str(rollout),
        "--report",
        str(report),
        "--device",
        "cpu",
        "--max-steps",
        str(max_steps),
        "--viewer",
        "headless",
        # Match the deployment DP tactile input: oracle-smoothed source-mesh
        # normals (inward convention, same as the training file).
        "--dp-tactile-normal-source",
        "source_mesh_oracle",
        "--allow-privileged-surface-oracle",
        *extra_args,
    ]
    with log.open("w") as log_stream:
        completed = subprocess.run(
            command,
            stdout=log_stream,
            stderr=subprocess.STDOUT,
        )
    tail = ""
    if log.is_file():
        tail = log.read_text(encoding="utf-8", errors="replace")[-600:]
    return {
        "episode_id": episode_id,
        "rollout": str(rollout),
        "returncode": completed.returncode,
        "log": str(log),
        "log_tail": tail,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--file", type=Path, required=True,
                        help="Inverted teacher H5 (the deployment eval source)")
    parser.add_argument("--model", type=Path, required=True,
                        help="Frozen deployment checkpoint (config only; policy never called)")
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--episodes", default="all",
                        help="Comma-separated episode ids, or 'all' (default)")
    parser.add_argument("--max-steps", type=int, default=2500)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--resume", action="store_true",
                        help="Skip episodes whose rollout H5 is already complete")
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument(
        "--frozen-mcc", action=argparse.BooleanOptionalAction, default=True,
        help="Apply the frozen §32 deployment MCC settings (default on).",
    )
    args = parser.parse_args()

    out_dir = args.out_dir
    (out_dir / "reports").mkdir(parents=True, exist_ok=True)
    (out_dir / "logs").mkdir(parents=True, exist_ok=True)

    with h5py.File(args.file, "r") as file:
        all_ids = sorted(
            {int(value) for value in file["episode_id"][:, 0]}
        )
    if args.episodes == "all":
        episode_ids = all_ids
    else:
        episode_ids = [int(token) for token in args.episodes.split(",")]
    unknown = [episode_id for episode_id in episode_ids if episode_id not in all_ids]
    if unknown:
        raise ValueError(f"Episode ids not in teacher file: {unknown}")
    if not episode_ids:
        raise ValueError("No episodes selected")

    extra_args = list(FROZEN_MCC_DEFAULTS.items()) if args.frozen_mcc else []
    extra_args = [flag for pair in extra_args for flag in pair]
    print(
        f"[COLLECT] {len(episode_ids)} episodes, workers={args.workers}, "
        f"max_steps={args.max_steps}, resume={args.resume}, "
        f"extra_args={' '.join(extra_args) or '(defaults)'}",
        flush=True,
    )

    results: list[dict[str, object]] = []
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = []
        for episode_id in episode_ids:
            expected = _expected_frames(args.file, episode_id, args.max_steps)
            rollout = out_dir / f"ep{episode_id:04d}.h5"
            if args.resume and _rollout_complete(rollout, expected):
                print(
                    f"[COLLECT] ep {episode_id}: skip (rollout already "
                    f"{rollout.stat().st_size} bytes)",
                    flush=True,
                )
                results.append(
                    {
                        "episode_id": episode_id,
                        "rollout": str(rollout),
                        "returncode": 0,
                        "skipped": True,
                    }
                )
                continue
            futures.append(
                pool.submit(
                    _run_episode,
                    args.file,
                    args.model,
                    out_dir,
                    episode_id,
                    args.max_steps,
                    extra_args,
                    args.python,
                )
            )
        for future in futures:
            result = future.result()
            results.append(result)
            status = "OK" if result["returncode"] == 0 else f"FAIL rc={result['returncode']}"
            print(
                f"[COLLECT] ep {result['episode_id']}: {status} -> {result['rollout']}",
                flush=True,
            )
            if result["returncode"] != 0:
                print(result.get("log_tail", ""), flush=True)

    results.sort(key=lambda row: int(row["episode_id"]))
    manifest = {
        "teacher_file": str(args.file),
        "model": str(args.model),
        "out_dir": str(out_dir),
        "max_steps": args.max_steps,
        "workers": args.workers,
        "resume": args.resume,
        "extra_args": extra_args,
        "episodes_requested": episode_ids,
        "ok": sum(1 for row in results if row["returncode"] == 0),
        "failed": sum(1 for row in results if row["returncode"] != 0),
        "records": results,
    }
    manifest_path = out_dir / "collect_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    failed = [row["episode_id"] for row in results if row["returncode"] != 0]
    print(
        f"[COLLECT] done: {manifest['ok']} ok / {manifest['failed']} failed "
        f"/ {len(results)} total; manifest -> {manifest_path}",
        flush=True,
    )
    if failed:
        print(f"[COLLECT] failed episodes (rerun with --resume): {failed}", flush=True)


if __name__ == "__main__":
    main()
